name: production
on:
  branch:
    - main
protection_rules:
  required_reviewers:
    min_reviewers: 1
  required_status_checks:
    strict: true
    contexts:
      - build-and-test
      - docker-build
  deployment_branch_policy:
    protected_branches: true
    custom_branch_policies: false
